<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Models\G_140000_fix42_float32.tflite" />
    <None Remove="Models\G_140000_float32.tflite" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Models\G_140000_fix42_float32.tflite" />
    <EmbeddedResource Include="Models\G_140000_float32.tflite" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
    <PackageReference Include="Microsoft.ML" Version="2.0.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.13.1" />
    <PackageReference Include="Microsoft.ML.OnnxTransformer" Version="2.0.0" />
    <PackageReference Include="NAudio" Version="2.1.0" />
  </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TensorFlowLite\TensorFlowLite.csproj" />
    </ItemGroup>

</Project>